#!/usr/bin/python

"""
pyv - this is a simple script that will use the pkg_resources module to quickly
determine the version of a given python module.
"""

# Import Statements
import argparse
import pkg_resources

def main():
    # parse the arguments
    parser = argparse.ArgumentParser(description='Get Python module version info')
    parser.add_argument('name', help='name of the module')
    parser.add_argument('-v', '--verbose', action="store_true",
        help='get verbose output')
    args = parser.parse_args()

    module_name = args.name
    try:
        info = pkg_resources.get_distribution(module_name)
        name = info.project_name
        version = info.version
        location = info.location
        if args.verbose:
            print name + " " + version + " (" + location + ")"
        else:
            print version
    except pkg_resources.DistributionNotFound:
        print "No distribution named " + module_name

if __name__ == '__main__':
    main()

